# Suggested data paths when using GPT-NeoX locally
{
  # "data-path": "data/enwik8/enwik8_text_document",

  # or for weighted datasets:
  "train-data-paths":
    [
      "/root/ft_data/OIG/tokenized/unified_ni/_text_document",
      # "/root/ft_data/OIG/tokenized/unified_p3/_text_document",
      "/root/ft_data/OIG/tokenized/unified_flan/_text_document",
      "/root/ft_data/OIG/tokenized/unified_chip2/_text_document",
      "/root/ft_data/OIG/tokenized/unified_rallio_safety_and_prosocial/_text_document",
      "/root/ft_data/OIG/tokenized/unified_soda_dialog/_text_document",
      "/root/ft_data/OIG/tokenized/unified_unifiedskg_instructions/_text_document",
      "/root/ft_data/OIG/tokenized/unified_merged_code_xp3/_text_document",
      "/root/ft_data/OIG/tokenized/unified_oscar_en_sample_dialog/_text_document",
      "/root/ft_data/OIG/tokenized/unified_ul2_plus_oscar_en_sample_dialog/_text_document",
      "/root/ft_data/OIG/tokenized/unified_multi_news/_text_document",
      "/root/ft_data/OIG/tokenized/unified_openai_summarize_tldr/_text_document",
      "/root/ft_data/OIG/tokenized/unified_squad_v2/_text_document",
      "/root/ft_data/OIG/tokenized/unified_nq/_text_document",
      "/root/ft_data/OIG/tokenized/unified_poetry_instructions/_text_document",
      "/root/ft_data/OIG/tokenized/unified_sqlv2/_text_document",
      "/root/ft_data/OIG/tokenized/unified_unnatural_instructions/_text_document",
      "/root/ft_data/OIG/tokenized/unified_conv_finqa/_text_document",
      "/root/ft_data/OIG/tokenized/unified_essays/_text_document",
      "/root/ft_data/OIG/tokenized/unified_plot_screenplay_books_dialog/_text_document",
      "/root/ft_data/OIG/tokenized/unified_grade_school_math_instructions/_text_document",
      "/root/ft_data/OIG/tokenized/unified_mathqa_flanv2_kojma_cot/_text_document",
      "/root/ft_data/OIG/tokenized/unified_joke_explanations/_text_document",
      "/root/ft_data/OIG/tokenized/unified_cuad/_text_document",
      "/root/ft_data/OIG/tokenized/unified_abstract_infill/_text_document",
      "/root/ft_data/OIG/tokenized/unified_image_prompts_instructions/_text_document",
    ],
  "test-data-paths": ["/root/ft_data/OIG/tokenized/unified_image_prompts_instructions/_text_document"],
  "valid-data-paths": ["/root/ft_data/OIG/tokenized/unified_image_prompts_instructions/_text_document"],
  "train-data-weights":
    [
      0.7,
      # 0.5,
      0.2,
      0.01,
      0.1,
      0.1,
      0.1,
      0.1,
      0.1,
      0.1,
      0.05,
      0.05,
      0.01,
      0.01,
      0.01,
      0.01,
      0.01,
      0.01,
      0.01,
      0.01,
      0.01,
      0.01,
      0.01,
      0.01,
      0.1,
      0.01,
    ],
  "test-data-weights": [1.,],
  "valid-data-weights": [1.,],

  # If weight_by_num_documents is True, Builds dataset weights from a multinomial distribution over groups of data according to the number of documents in each group.
  # WARNING: setting this to True will override any user provided weights
  # "weight_by_num_documents": false,
  # "weighted_sampler_alpha": 0.3,
  "tokenizer_type": "HFTokenizer",
  "vocab-file": "/root/ft_data/meta/20B_tokenizer.json",
  # "merge-file": "/root/fm/config/gpt2-merges.txt",
  # "finetune": True,
  "save": "/root/fm/models/ckpts/model_checkpoints",
  "load": "/root/fm/models/ckpts/model_global_step100000",
  "checkpoint_validation_with_forward_pass": False,
  "tensorboard-dir": "tensorboard",
  "log-dir": "logs",
  "use_wandb": True,
  "wandb_host": "https://api.wandb.ai",
  "wandb_project": "neox",
}
